# Project: zhizhenpractice1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../algorithm/zhizhenpractice1.o
LINKOBJ  = ../algorithm/zhizhenpractice1.o
LIBS     = -L"D:/softwareinstall/Dev-C++/dec-cpp install/Dev-Cpp/MinGW64/lib" -L"D:/softwareinstall/Dev-C++/dec-cpp install/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/softwareinstall/Dev-C++/dec-cpp install/Dev-Cpp/MinGW64/include" -I"D:/softwareinstall/Dev-C++/dec-cpp install/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/softwareinstall/Dev-C++/dec-cpp install/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/softwareinstall/Dev-C++/dec-cpp install/Dev-Cpp/MinGW64/include" -I"D:/softwareinstall/Dev-C++/dec-cpp install/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/softwareinstall/Dev-C++/dec-cpp install/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/softwareinstall/Dev-C++/dec-cpp install/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = zhizhenpractice1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

../algorithm/zhizhenpractice1.o: ../algorithm/zhizhenpractice1.c
	$(CC) -c ../algorithm/zhizhenpractice1.c -o ../algorithm/zhizhenpractice1.o $(CFLAGS)
